version: '3.3'
services: 
  master:
    container_name: master
    hostname: master
    image: ansible_master
    build:
      context: master
    volumes:
      - ./m_play_dir:/root/ansible/playbooksDir
    networks:
      - net
  worker1:
    container_name: worker_node_1
    hostname: worker1
    image: sshd_basic
    build:
      context: ./worker_node
      dockerfile: Dockerfile_test
    networks:
      - net
  worker2:
    container_name: worker_node_2
    hostname: worker2
    image: sshd_basic
    networks:
      - net
networks:
  net:
