on: '3.3'
services: 
  master:
    container_name: master
    image: ansible_master
    build:
      context: master
    volumes:
      - ./m_play_dir:/root/ansible/playbooksDir
    networks:
      - net
  worker1:
    container_name: worker_node_1
    image: sshd_basic
    build:
      context: ./worker_node
      dockerfile: Dockerfile_test
    volumes:
      - /sys/fs/cgroup/:/sys/fs/cgroup:ro
    cap_add:
      - SYS_ADMIN
    networks:
      - net
  worker2:
    container_name: worker_node_2
    image: sshd_basic
    volumes:
      - /sys/fs/cgroup/:/sys/fs/cgroup:ro
    cap_add:
      - SYS_ADMIN
    networks:
      - net
networks:
  net:
