version: '3.3'
services: 
  master:
    container_name: master
    image: ansible_master
    build:
      context: master
    volumes:
      - m_play_dir:/root/ansible/playbooksDir
    networks:
      - net
  worker1:
    container_name: worker_node_1
    image: ansible_worker
    build:
      context: worker_node
    networks:
      - net
  worker2:
    container_name: worker_node_2
    image: ansible_worker
    networks:
      - net
networks:
  net:
