- name: Play1
  hosts: all
  become: yes
  tasks:
    - name: Installing the httpd
      package:
        name: httpd
        state: present

    - name: Starting the service
      service:
        name: httpd
        state: started
        enabled: true

    - name: Creating a file
      file:
        path: /var/www/html/index.html
        state: touch

    - name: Adding a line to file
      copy:
        dest: /var/www/html/index.html
        content: |
          Testing Ansible on {{ inventory_hostname }}

    - name: Starting the service
      service:
        name: httpd
        state: restarted

